"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-me')
DEBUG = os.getenv('DEBUG', '1') == '1'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',  # gestion des tokens JWT
    'drf_spectacular',            # génération automatique de la doc Swagger
    'corsheaders',
      # Application qui gère les utilisateurs et l'authentification
    'accounts',
    'demandes',         # demandes de sang + sollicitations
    'participations',   # participations des donneurs
    'dashboard',
    'rag', 

]

# Indiquer à Django d'utiliser notre modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'accounts.Utilisateur'

REST_FRAMEWORK = {
    # Toutes les vues utiliseront JWT pour identifier l'utilisateur connecté
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # drf-spectacular génère le schéma OpenAPI utilisé par Swagger
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'bloodsen'),
        'USER': os.getenv('DATABASE_USER', 'bloodsen'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'bloodsen_password'),
        'HOST': os.getenv('DATABASE_HOST', 'db'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:5173'
).split(',')

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Dakar'

# ========================================
# JWT — durée de vie des tokens
# ========================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),   # le token d'accès expire après 1h
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # le refresh token expire après 7 jours
    'ROTATE_REFRESH_TOKENS': True,  # un nouveau refresh token est généré à chaque rafraîchissement
}

# ========================================
# SWAGGER — informations affichées sur la doc
# ========================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'BloodSen API',
    'DESCRIPTION': 'API de la plateforme BloodSen — mise en relation donneurs / structures de santé',
    'VERSION': '1.0.0',
}


# Backend utilisé pour envoyer les emails
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)

# Adresse du serveur SMTP de Gmail
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')

# Port utilisé par Gmail pour envoyer les emails
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))

# Activer la sécurité TLS
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', '1') == '1'

# Adresse email utilisée pour envoyer les messages
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')

# Mot de passe de l'adresse email
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Adresse affichée comme expéditeur
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '')

# URL du frontend Vue utilisée dans le lien de vérification
FRONTEND_URL = os.getenv(
    'FRONTEND_URL',
    'http://localhost:5173'
)


# ======================================
# CONFIGURATION RAG (chatbot sur les dons de sang)
# ======================================

# Clé API Cohere (utilisée pour les embeddings)
COHERE_API_KEY = os.getenv('COHERE_API_KEY', '')

# Modèle d'embedding Cohere (1024 dimensions, multilingue)
COHERE_EMBED_MODEL = 'embed-multilingual-v3.0'

# Nombre de dimensions des vecteurs (doit matcher COHERE_EMBED_MODEL)
# et le champ DocumentChunk.embedding
RAG_EMBEDDING_DIMENSIONS = 1024

# Taille des chunks (en mots) et chevauchement
RAG_CHUNK_SIZE = 500
RAG_CHUNK_OVERLAP = 50

# Clé API Groq (utilisée pour la génération de réponses)
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')

# Modèle LLM Groq à utiliser
GROQ_MODEL = 'openai/gpt-oss-120b'

# Nombre maximum de chunks à envoyer au LLM comme contexte
RAG_MAX_CHUNKS = 5

# Seuil de similarité (distance cosinus maximale pour qu'un chunk soit gardé)
RAG_SIMILARITY_THRESHOLD = 0.5


# ======================================
# FICHIERS MÉDIA (uploads utilisateur)
# ======================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'