# Generated by Django 5.0.14 on 2026-09-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='confirmee', max_length=20)),
                ('date_confirmation', models.DateTimeField(auto_now_add=True)),
                ('sollicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='demandes.sollicitation')),
            ],
        ),
    ]
