# Generated by Django 5.0.14 on 2026-09-17 15:33

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre lisible du document (ex: 'Guide du don de sang - OMS')", max_length=255)),
                ('fichier', models.FileField(help_text='Le fichier PDF uploadé', upload_to='rag_documents/')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du contenu du document')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, help_text="Si False, le document n'est plus utilisé pour répondre aux questions")),
                ('ajoute_par', models.ForeignKey(help_text='Superuser qui a uploadé le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Le texte de ce morceau')),
                ('ordre', models.PositiveIntegerField(help_text='Position du chunk dans le document (0, 1, 2, ...)')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, help_text='Vecteur produit par Cohere (embed-multilingual-v3)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
            ],
            options={
                'ordering': ['document', 'ordre'],
                'unique_together': {('document', 'ordre')},
            },
        ),
    ]
