# Generated by Django 5.0.14 on 2026-09-25 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenReinitialisationMotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expire_a', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False, help_text='True si le token a déjà servi (à usage unique)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_reinitialisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
