# Generated by Django 5.0.14 on 2026-10-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_createur', models.CharField(choices=[('structure', 'Structure de santé'), ('proche', 'Proche (utilisateur connecté)'), ('public', 'Personne sans compte')], default='structure', max_length=20)),
                ('groupe_sanguin', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantite', models.PositiveIntegerField()),
                ('urgence', models.CharField(choices=[('vitale', 'Urgence vitale'), ('urgent', 'Urgent'), ('programme', 'Programme')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_verification', 'En vérification'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField()),
                ('nom_demandeur', models.CharField(blank=True, max_length=200)),
                ('telephone_demandeur', models.CharField(blank=True, max_length=20)),
                ('telephone_verifie', models.BooleanField(default=False)),
                ('nom_patient', models.CharField(blank=True, max_length=200)),
                ('lieu_prise_en_charge', models.CharField(blank=True, max_length=255)),
                ('token_suivi', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('latitude_urgence', models.FloatField(blank=True, null=True)),
                ('longitude_urgence', models.FloatField(blank=True, null=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='accounts.profilstructuresante')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='accounts.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Sollicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sollicitations', to='demandes.demande')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sollicitations', to='accounts.profildonneur')),
            ],
            options={
                'unique_together': {('demande', 'donneur')},
            },
        ),
    ]
