# Generated by Django 5.0.14 on 2026-09-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantite', models.PositiveIntegerField(help_text='Nombre de poches de sang nécessaires')),
                ('urgence', models.CharField(choices=[('vitale', 'Urgence vitale'), ('urgent', 'Urgent'), ('programme', 'Programmé')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(help_text="Date/heure après laquelle la demande n'est plus valable")),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.profilstructuresante')),
            ],
        ),
        migrations.CreateModel(
            name='Sollicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, help_text='Date à laquelle le donneur a répondu (accepté ou refusé)', null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sollicitations', to='demandes.demande')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sollicitations', to='accounts.profildonneur')),
            ],
            options={
                'unique_together': {('demande', 'donneur')},
            },
        ),
    ]
