# Generated by Django 5.0.14 on 2026-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='email_demandeur',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
